#!/bin/sh

if [ -x $(which pwgen) ] ; then
  pwgen -Bs 12 1 | sed -E 's/(....)(....)(....)/\1-\2-\3/'
else
  cat /dev/urandom | tr -dc 'a-hjkmnp-zA-HJ-NP-Z2-9' | fold -w 12 | sed -E 's/(....)(....)(....)/\1-\2-\3/' | head -n 1
fi
