#!/bin/bash

usage()
{
  echo "Usage : ${0} [-B]"
}

str="a-km-zA-HJ-NP-Z2-9"

while getopts ":B" opt; do
  case ${opt} in
    B)
      str="a-km-zACEFHJ-NPRT-Y3479"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

cat /dev/urandom | tr -dc "${str}" | fold -w 12 | grep -E '[A-Z]' | grep -E '[0-9]' | sed -E 's/(....)(....)(....)/\1-\2-\3/' | head -n 1
