#!/bin/bash

usage()
{
  echo "Usage : $(basename ${0}) [-n num_pw] [-B]"
}

str="lIO01\+\/\="
num_pw=1

while getopts ":n:B" opt; do
  case ${opt} in
    n)
      num_pw=${OPTARG}
      ;;
    B)
      str="lBDGIOQS012568\+\/\="
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

cat /dev/urandom | base64 -w 0 | tr -d "${str}" | fold -w 12 | grep -E '[A-Z]' | grep -E '[0-9]' | sed -E 's/(....)(....)(....)/\1-\2-\3/' | head -n ${num_pw}
